version: '2'
services:
    cadastro-app:
        image: cadastro
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://cadastro-postgresql:5432/cadastro
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    cadastro-postgresql:
        extends:
            file: postgresql.yml
            service: cadastro-postgresql
